version: "2"
run:
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - "asasalint"
    - "asciicheck"
    - "bodyclose"
    - "canonicalheader"
    - "copyloopvar"
    - "dupl"
    - "dupword"
    - "errcheck"
    - "errchkjson"
    - "errname"
    - "errname"
    - "errorlint"
    - "gocheckcompilerdirectives"
    - "gochecksumtype"
    - "goconst"
    - "godoclint"
    - "gomoddirectives"
    - "gosec"
    - "gosmopolitan"
    - "govet"
    - "ineffassign"
    - "intrange"
    - "makezero"
    - "misspell"
    - "nilerr"
    - "noctx"
    - "nolintlint"
    - "paralleltest"
    - "perfsprint"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "sloglint"
    - "sqlclosecheck"
    - "staticcheck"
    - "tparallel"
    - "unconvert"
    - "unparam"
    - "unused"
    - "usestdlibvars"
    - "usetesting"
    - "whitespace"

formatters:
  enable:
    - "gci"
    - "gofumpt"
  settings:
    gci:
      sections:
        - "standard"
        - "default"
        - "localmodule"
      custom-order: true
