version: "2"
run:
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - "asasalint"
    - "bodyclose"
    - "copyloopvar"
    - "dupword"
    - "errcheck"
    - "errorlint"
    - "gosec"
    - "govet"
    - "ineffassign"
    - "nilerr"
    - "predeclared"
    - "revive"
    - "nilerr"
    - "nolintlint"
    - "staticcheck"
    - "tparallel"
    - "unconvert"
    - "unused"
    - "unparam"
    - "whitespace"

formatters:
  enable:
    - "gci"
    - "gofumpt"
  settings:
    gci:
      sections:
        - "standard"
        - "default"
        - "localmodule"
      custom-order: true
