// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: spacex_api/device/account_shard.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountShard int32

const (
	AccountShard_ACCOUNT_SHARD_UNKNOWN AccountShard = 0
	AccountShard_ACCOUNT_SHARD_DEFAULT AccountShard = 1
	AccountShard_ACCOUNT_SHARD_INDIA   AccountShard = 2
)

// Enum value maps for AccountShard.
var (
	AccountShard_name = map[int32]string{
		0: "ACCOUNT_SHARD_UNKNOWN",
		1: "ACCOUNT_SHARD_DEFAULT",
		2: "ACCOUNT_SHARD_INDIA",
	}
	AccountShard_value = map[string]int32{
		"ACCOUNT_SHARD_UNKNOWN": 0,
		"ACCOUNT_SHARD_DEFAULT": 1,
		"ACCOUNT_SHARD_INDIA":   2,
	}
)

func (x AccountShard) Enum() *AccountShard {
	p := new(AccountShard)
	*p = x
	return p
}

func (x AccountShard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountShard) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_account_shard_proto_enumTypes[0].Descriptor()
}

func (AccountShard) Type() protoreflect.EnumType {
	return &file_spacex_api_device_account_shard_proto_enumTypes[0]
}

func (x AccountShard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountShard.Descriptor instead.
func (AccountShard) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_account_shard_proto_rawDescGZIP(), []int{0}
}

var File_spacex_api_device_account_shard_proto protoreflect.FileDescriptor

const file_spacex_api_device_account_shard_proto_rawDesc = "" +
	"\n" +
	"%spacex_api/device/account_shard.proto\x12\x11SpaceX.API.Device*]\n" +
	"\fAccountShard\x12\x19\n" +
	"\x15ACCOUNT_SHARD_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_SHARD_DEFAULT\x10\x01\x12\x17\n" +
	"\x13ACCOUNT_SHARD_INDIA\x10\x02B%Z#spacex.com/api/device/account_shardb\x06proto3"

var (
	file_spacex_api_device_account_shard_proto_rawDescOnce sync.Once
	file_spacex_api_device_account_shard_proto_rawDescData []byte
)

func file_spacex_api_device_account_shard_proto_rawDescGZIP() []byte {
	file_spacex_api_device_account_shard_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_account_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacex_api_device_account_shard_proto_rawDesc), len(file_spacex_api_device_account_shard_proto_rawDesc)))
	})
	return file_spacex_api_device_account_shard_proto_rawDescData
}

var file_spacex_api_device_account_shard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spacex_api_device_account_shard_proto_goTypes = []any{
	(AccountShard)(0), // 0: SpaceX.API.Device.AccountShard
}
var file_spacex_api_device_account_shard_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spacex_api_device_account_shard_proto_init() }
func file_spacex_api_device_account_shard_proto_init() {
	if File_spacex_api_device_account_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacex_api_device_account_shard_proto_rawDesc), len(file_spacex_api_device_account_shard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_device_account_shard_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_account_shard_proto_depIdxs,
		EnumInfos:         file_spacex_api_device_account_shard_proto_enumTypes,
	}.Build()
	File_spacex_api_device_account_shard_proto = out.File
	file_spacex_api_device_account_shard_proto_goTypes = nil
	file_spacex_api_device_account_shard_proto_depIdxs = nil
}
