// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: spacex_api/device/command.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability int32

const (
	Capability_READ             Capability = 0
	Capability_READ_INTERNAL    Capability = 13
	Capability_READ_PRIVATE     Capability = 7
	Capability_LOCAL            Capability = 14
	Capability_WRITE            Capability = 1
	Capability_WRITE_PERSISTENT Capability = 11
	Capability_DEBUG            Capability = 2
	Capability_ADMIN            Capability = 3
	Capability_SETUP            Capability = 4
	Capability_SET_SKU          Capability = 5
	Capability_REFRESH          Capability = 6
	Capability_FUSE             Capability = 8
	Capability_RESET            Capability = 9
	Capability_TEST             Capability = 10
	Capability_SSH              Capability = 12
	Capability_GUEST            Capability = 15
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0:  "READ",
		13: "READ_INTERNAL",
		7:  "READ_PRIVATE",
		14: "LOCAL",
		1:  "WRITE",
		11: "WRITE_PERSISTENT",
		2:  "DEBUG",
		3:  "ADMIN",
		4:  "SETUP",
		5:  "SET_SKU",
		6:  "REFRESH",
		8:  "FUSE",
		9:  "RESET",
		10: "TEST",
		12: "SSH",
		15: "GUEST",
	}
	Capability_value = map[string]int32{
		"READ":             0,
		"READ_INTERNAL":    13,
		"READ_PRIVATE":     7,
		"LOCAL":            14,
		"WRITE":            1,
		"WRITE_PERSISTENT": 11,
		"DEBUG":            2,
		"ADMIN":            3,
		"SETUP":            4,
		"SET_SKU":          5,
		"REFRESH":          6,
		"FUSE":             8,
		"RESET":            9,
		"TEST":             10,
		"SSH":              12,
		"GUEST":            15,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_command_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_spacex_api_device_command_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_command_proto_rawDescGZIP(), []int{0}
}

type User int32

const (
	User_NO_USER              User = 0
	User_GOD                  User = 1
	User_LAN                  User = 2
	User_CLOUD                User = 3
	User_FACTORY              User = 4
	User_ROUTER               User = 5
	User_GUEST_LAN            User = 6
	User_SENSITIVE_COMMANDING User = 7
	User_LAN_TLS              User = 8
)

// Enum value maps for User.
var (
	User_name = map[int32]string{
		0: "NO_USER",
		1: "GOD",
		2: "LAN",
		3: "CLOUD",
		4: "FACTORY",
		5: "ROUTER",
		6: "GUEST_LAN",
		7: "SENSITIVE_COMMANDING",
		8: "LAN_TLS",
	}
	User_value = map[string]int32{
		"NO_USER":              0,
		"GOD":                  1,
		"LAN":                  2,
		"CLOUD":                3,
		"FACTORY":              4,
		"ROUTER":               5,
		"GUEST_LAN":            6,
		"SENSITIVE_COMMANDING": 7,
		"LAN_TLS":              8,
	}
)

func (x User) Enum() *User {
	p := new(User)
	*p = x
	return p
}

func (x User) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_command_proto_enumTypes[1].Descriptor()
}

func (User) Type() protoreflect.EnumType {
	return &file_spacex_api_device_command_proto_enumTypes[1]
}

func (x User) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User.Descriptor instead.
func (User) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_command_proto_rawDescGZIP(), []int{1}
}

type PublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Deprecated: Marked as deprecated in spacex_api/device/command.proto.
	Capabilities  []Capability `protobuf:"varint,2,rep,packed,name=capabilities,proto3,enum=SpaceX.API.Device.Capability" json:"capabilities,omitempty"`
	User          User         `protobuf:"varint,3,opt,name=user,proto3,enum=SpaceX.API.Device.User" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_spacex_api_device_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_command_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Deprecated: Marked as deprecated in spacex_api/device/command.proto.
func (x *PublicKey) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PublicKey) GetUser() User {
	if x != nil {
		return x.User
	}
	return User_NO_USER
}

var File_spacex_api_device_command_proto protoreflect.FileDescriptor

const file_spacex_api_device_command_proto_rawDesc = "" +
	"\n" +
	"\x1fspacex_api/device/command.proto\x12\x11SpaceX.API.Device\"\x91\x01\n" +
	"\tPublicKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12E\n" +
	"\fcapabilities\x18\x02 \x03(\x0e2\x1d.SpaceX.API.Device.CapabilityB\x02\x18\x01R\fcapabilities\x12+\n" +
	"\x04user\x18\x03 \x01(\x0e2\x17.SpaceX.API.Device.UserR\x04user*\xd5\x01\n" +
	"\n" +
	"Capability\x12\b\n" +
	"\x04READ\x10\x00\x12\x11\n" +
	"\rREAD_INTERNAL\x10\r\x12\x10\n" +
	"\fREAD_PRIVATE\x10\a\x12\t\n" +
	"\x05LOCAL\x10\x0e\x12\t\n" +
	"\x05WRITE\x10\x01\x12\x14\n" +
	"\x10WRITE_PERSISTENT\x10\v\x12\t\n" +
	"\x05DEBUG\x10\x02\x12\t\n" +
	"\x05ADMIN\x10\x03\x12\t\n" +
	"\x05SETUP\x10\x04\x12\v\n" +
	"\aSET_SKU\x10\x05\x12\v\n" +
	"\aREFRESH\x10\x06\x12\b\n" +
	"\x04FUSE\x10\b\x12\t\n" +
	"\x05RESET\x10\t\x12\b\n" +
	"\x04TEST\x10\n" +
	"\x12\a\n" +
	"\x03SSH\x10\f\x12\t\n" +
	"\x05GUEST\x10\x0f*\x7f\n" +
	"\x04User\x12\v\n" +
	"\aNO_USER\x10\x00\x12\a\n" +
	"\x03GOD\x10\x01\x12\a\n" +
	"\x03LAN\x10\x02\x12\t\n" +
	"\x05CLOUD\x10\x03\x12\v\n" +
	"\aFACTORY\x10\x04\x12\n" +
	"\n" +
	"\x06ROUTER\x10\x05\x12\r\n" +
	"\tGUEST_LAN\x10\x06\x12\x18\n" +
	"\x14SENSITIVE_COMMANDING\x10\a\x12\v\n" +
	"\aLAN_TLS\x10\bB\x17Z\x15spacex.com/api/deviceb\x06proto3"

var (
	file_spacex_api_device_command_proto_rawDescOnce sync.Once
	file_spacex_api_device_command_proto_rawDescData []byte
)

func file_spacex_api_device_command_proto_rawDescGZIP() []byte {
	file_spacex_api_device_command_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacex_api_device_command_proto_rawDesc), len(file_spacex_api_device_command_proto_rawDesc)))
	})
	return file_spacex_api_device_command_proto_rawDescData
}

var file_spacex_api_device_command_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spacex_api_device_command_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spacex_api_device_command_proto_goTypes = []any{
	(Capability)(0),   // 0: SpaceX.API.Device.Capability
	(User)(0),         // 1: SpaceX.API.Device.User
	(*PublicKey)(nil), // 2: SpaceX.API.Device.PublicKey
}
var file_spacex_api_device_command_proto_depIdxs = []int32{
	0, // 0: SpaceX.API.Device.PublicKey.capabilities:type_name -> SpaceX.API.Device.Capability
	1, // 1: SpaceX.API.Device.PublicKey.user:type_name -> SpaceX.API.Device.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spacex_api_device_command_proto_init() }
func file_spacex_api_device_command_proto_init() {
	if File_spacex_api_device_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacex_api_device_command_proto_rawDesc), len(file_spacex_api_device_command_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_device_command_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_command_proto_depIdxs,
		EnumInfos:         file_spacex_api_device_command_proto_enumTypes,
		MessageInfos:      file_spacex_api_device_command_proto_msgTypes,
	}.Build()
	File_spacex_api_device_command_proto = out.File
	file_spacex_api_device_command_proto_goTypes = nil
	file_spacex_api_device_command_proto_depIdxs = nil
}
