// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: spacex_api/device/dish_config.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DishConfig_SnowMeltMode int32

const (
	DishConfig_AUTO       DishConfig_SnowMeltMode = 0
	DishConfig_ALWAYS_ON  DishConfig_SnowMeltMode = 1
	DishConfig_ALWAYS_OFF DishConfig_SnowMeltMode = 2
)

// Enum value maps for DishConfig_SnowMeltMode.
var (
	DishConfig_SnowMeltMode_name = map[int32]string{
		0: "AUTO",
		1: "ALWAYS_ON",
		2: "ALWAYS_OFF",
	}
	DishConfig_SnowMeltMode_value = map[string]int32{
		"AUTO":       0,
		"ALWAYS_ON":  1,
		"ALWAYS_OFF": 2,
	}
)

func (x DishConfig_SnowMeltMode) Enum() *DishConfig_SnowMeltMode {
	p := new(DishConfig_SnowMeltMode)
	*p = x
	return p
}

func (x DishConfig_SnowMeltMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DishConfig_SnowMeltMode) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_dish_config_proto_enumTypes[0].Descriptor()
}

func (DishConfig_SnowMeltMode) Type() protoreflect.EnumType {
	return &file_spacex_api_device_dish_config_proto_enumTypes[0]
}

func (x DishConfig_SnowMeltMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DishConfig_SnowMeltMode.Descriptor instead.
func (DishConfig_SnowMeltMode) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_dish_config_proto_rawDescGZIP(), []int{0, 0}
}

type DishConfig_LocationRequestMode int32

const (
	DishConfig_NONE  DishConfig_LocationRequestMode = 0
	DishConfig_LOCAL DishConfig_LocationRequestMode = 1
)

// Enum value maps for DishConfig_LocationRequestMode.
var (
	DishConfig_LocationRequestMode_name = map[int32]string{
		0: "NONE",
		1: "LOCAL",
	}
	DishConfig_LocationRequestMode_value = map[string]int32{
		"NONE":  0,
		"LOCAL": 1,
	}
)

func (x DishConfig_LocationRequestMode) Enum() *DishConfig_LocationRequestMode {
	p := new(DishConfig_LocationRequestMode)
	*p = x
	return p
}

func (x DishConfig_LocationRequestMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DishConfig_LocationRequestMode) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_dish_config_proto_enumTypes[1].Descriptor()
}

func (DishConfig_LocationRequestMode) Type() protoreflect.EnumType {
	return &file_spacex_api_device_dish_config_proto_enumTypes[1]
}

func (x DishConfig_LocationRequestMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DishConfig_LocationRequestMode.Descriptor instead.
func (DishConfig_LocationRequestMode) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_dish_config_proto_rawDescGZIP(), []int{0, 1}
}

type DishConfig_LevelDishMode int32

const (
	DishConfig_TILT_LIKE_NORMAL DishConfig_LevelDishMode = 0
	DishConfig_FORCE_LEVEL      DishConfig_LevelDishMode = 1
)

// Enum value maps for DishConfig_LevelDishMode.
var (
	DishConfig_LevelDishMode_name = map[int32]string{
		0: "TILT_LIKE_NORMAL",
		1: "FORCE_LEVEL",
	}
	DishConfig_LevelDishMode_value = map[string]int32{
		"TILT_LIKE_NORMAL": 0,
		"FORCE_LEVEL":      1,
	}
)

func (x DishConfig_LevelDishMode) Enum() *DishConfig_LevelDishMode {
	p := new(DishConfig_LevelDishMode)
	*p = x
	return p
}

func (x DishConfig_LevelDishMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DishConfig_LevelDishMode) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_dish_config_proto_enumTypes[2].Descriptor()
}

func (DishConfig_LevelDishMode) Type() protoreflect.EnumType {
	return &file_spacex_api_device_dish_config_proto_enumTypes[2]
}

func (x DishConfig_LevelDishMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DishConfig_LevelDishMode.Descriptor instead.
func (DishConfig_LevelDishMode) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_dish_config_proto_rawDescGZIP(), []int{0, 2}
}

type DishConfig struct {
	state                                protoimpl.MessageState         `protogen:"open.v1"`
	SnowMeltMode                         DishConfig_SnowMeltMode        `protobuf:"varint,1,opt,name=snow_melt_mode,json=snowMeltMode,proto3,enum=SpaceX.API.Device.DishConfig_SnowMeltMode" json:"snow_melt_mode,omitempty"`
	ApplySnowMeltMode                    bool                           `protobuf:"varint,1001,opt,name=apply_snow_melt_mode,json=applySnowMeltMode,proto3" json:"apply_snow_melt_mode,omitempty"`
	LocationRequestMode                  DishConfig_LocationRequestMode `protobuf:"varint,2,opt,name=location_request_mode,json=locationRequestMode,proto3,enum=SpaceX.API.Device.DishConfig_LocationRequestMode" json:"location_request_mode,omitempty"`
	ApplyLocationRequestMode             bool                           `protobuf:"varint,2001,opt,name=apply_location_request_mode,json=applyLocationRequestMode,proto3" json:"apply_location_request_mode,omitempty"`
	LevelDishMode                        DishConfig_LevelDishMode       `protobuf:"varint,3,opt,name=level_dish_mode,json=levelDishMode,proto3,enum=SpaceX.API.Device.DishConfig_LevelDishMode" json:"level_dish_mode,omitempty"`
	ApplyLevelDishMode                   bool                           `protobuf:"varint,3001,opt,name=apply_level_dish_mode,json=applyLevelDishMode,proto3" json:"apply_level_dish_mode,omitempty"`
	PowerSaveStartMinutes                uint32                         `protobuf:"varint,4,opt,name=power_save_start_minutes,json=powerSaveStartMinutes,proto3" json:"power_save_start_minutes,omitempty"`
	ApplyPowerSaveStartMinutes           bool                           `protobuf:"varint,4001,opt,name=apply_power_save_start_minutes,json=applyPowerSaveStartMinutes,proto3" json:"apply_power_save_start_minutes,omitempty"`
	PowerSaveDurationMinutes             uint32                         `protobuf:"varint,5,opt,name=power_save_duration_minutes,json=powerSaveDurationMinutes,proto3" json:"power_save_duration_minutes,omitempty"`
	ApplyPowerSaveDurationMinutes        bool                           `protobuf:"varint,5001,opt,name=apply_power_save_duration_minutes,json=applyPowerSaveDurationMinutes,proto3" json:"apply_power_save_duration_minutes,omitempty"`
	PowerSaveMode                        bool                           `protobuf:"varint,6,opt,name=power_save_mode,json=powerSaveMode,proto3" json:"power_save_mode,omitempty"`
	ApplyPowerSaveMode                   bool                           `protobuf:"varint,6001,opt,name=apply_power_save_mode,json=applyPowerSaveMode,proto3" json:"apply_power_save_mode,omitempty"`
	SwupdateRebootHour                   uint32                         `protobuf:"varint,9,opt,name=swupdate_reboot_hour,json=swupdateRebootHour,proto3" json:"swupdate_reboot_hour,omitempty"`
	ApplySwupdateRebootHour              bool                           `protobuf:"varint,9001,opt,name=apply_swupdate_reboot_hour,json=applySwupdateRebootHour,proto3" json:"apply_swupdate_reboot_hour,omitempty"`
	SwupdateThreeDayDeferralEnabled      bool                           `protobuf:"varint,7,opt,name=swupdate_three_day_deferral_enabled,json=swupdateThreeDayDeferralEnabled,proto3" json:"swupdate_three_day_deferral_enabled,omitempty"`
	ApplySwupdateThreeDayDeferralEnabled bool                           `protobuf:"varint,7001,opt,name=apply_swupdate_three_day_deferral_enabled,json=applySwupdateThreeDayDeferralEnabled,proto3" json:"apply_swupdate_three_day_deferral_enabled,omitempty"`
	AssetClass                           uint32                         `protobuf:"varint,8,opt,name=asset_class,json=assetClass,proto3" json:"asset_class,omitempty"`
	ApplyAssetClass                      bool                           `protobuf:"varint,8001,opt,name=apply_asset_class,json=applyAssetClass,proto3" json:"apply_asset_class,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *DishConfig) Reset() {
	*x = DishConfig{}
	mi := &file_spacex_api_device_dish_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishConfig) ProtoMessage() {}

func (x *DishConfig) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_dish_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishConfig.ProtoReflect.Descriptor instead.
func (*DishConfig) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_dish_config_proto_rawDescGZIP(), []int{0}
}

func (x *DishConfig) GetSnowMeltMode() DishConfig_SnowMeltMode {
	if x != nil {
		return x.SnowMeltMode
	}
	return DishConfig_AUTO
}

func (x *DishConfig) GetApplySnowMeltMode() bool {
	if x != nil {
		return x.ApplySnowMeltMode
	}
	return false
}

func (x *DishConfig) GetLocationRequestMode() DishConfig_LocationRequestMode {
	if x != nil {
		return x.LocationRequestMode
	}
	return DishConfig_NONE
}

func (x *DishConfig) GetApplyLocationRequestMode() bool {
	if x != nil {
		return x.ApplyLocationRequestMode
	}
	return false
}

func (x *DishConfig) GetLevelDishMode() DishConfig_LevelDishMode {
	if x != nil {
		return x.LevelDishMode
	}
	return DishConfig_TILT_LIKE_NORMAL
}

func (x *DishConfig) GetApplyLevelDishMode() bool {
	if x != nil {
		return x.ApplyLevelDishMode
	}
	return false
}

func (x *DishConfig) GetPowerSaveStartMinutes() uint32 {
	if x != nil {
		return x.PowerSaveStartMinutes
	}
	return 0
}

func (x *DishConfig) GetApplyPowerSaveStartMinutes() bool {
	if x != nil {
		return x.ApplyPowerSaveStartMinutes
	}
	return false
}

func (x *DishConfig) GetPowerSaveDurationMinutes() uint32 {
	if x != nil {
		return x.PowerSaveDurationMinutes
	}
	return 0
}

func (x *DishConfig) GetApplyPowerSaveDurationMinutes() bool {
	if x != nil {
		return x.ApplyPowerSaveDurationMinutes
	}
	return false
}

func (x *DishConfig) GetPowerSaveMode() bool {
	if x != nil {
		return x.PowerSaveMode
	}
	return false
}

func (x *DishConfig) GetApplyPowerSaveMode() bool {
	if x != nil {
		return x.ApplyPowerSaveMode
	}
	return false
}

func (x *DishConfig) GetSwupdateRebootHour() uint32 {
	if x != nil {
		return x.SwupdateRebootHour
	}
	return 0
}

func (x *DishConfig) GetApplySwupdateRebootHour() bool {
	if x != nil {
		return x.ApplySwupdateRebootHour
	}
	return false
}

func (x *DishConfig) GetSwupdateThreeDayDeferralEnabled() bool {
	if x != nil {
		return x.SwupdateThreeDayDeferralEnabled
	}
	return false
}

func (x *DishConfig) GetApplySwupdateThreeDayDeferralEnabled() bool {
	if x != nil {
		return x.ApplySwupdateThreeDayDeferralEnabled
	}
	return false
}

func (x *DishConfig) GetAssetClass() uint32 {
	if x != nil {
		return x.AssetClass
	}
	return 0
}

func (x *DishConfig) GetApplyAssetClass() bool {
	if x != nil {
		return x.ApplyAssetClass
	}
	return false
}

var File_spacex_api_device_dish_config_proto protoreflect.FileDescriptor

const file_spacex_api_device_dish_config_proto_rawDesc = "" +
	"\n" +
	"#spacex_api/device/dish_config.proto\x12\x11SpaceX.API.Device\"\xa7\n" +
	"\n" +
	"\n" +
	"DishConfig\x12P\n" +
	"\x0esnow_melt_mode\x18\x01 \x01(\x0e2*.SpaceX.API.Device.DishConfig.SnowMeltModeR\fsnowMeltMode\x120\n" +
	"\x14apply_snow_melt_mode\x18\xe9\a \x01(\bR\x11applySnowMeltMode\x12e\n" +
	"\x15location_request_mode\x18\x02 \x01(\x0e21.SpaceX.API.Device.DishConfig.LocationRequestModeR\x13locationRequestMode\x12>\n" +
	"\x1bapply_location_request_mode\x18\xd1\x0f \x01(\bR\x18applyLocationRequestMode\x12S\n" +
	"\x0flevel_dish_mode\x18\x03 \x01(\x0e2+.SpaceX.API.Device.DishConfig.LevelDishModeR\rlevelDishMode\x122\n" +
	"\x15apply_level_dish_mode\x18\xb9\x17 \x01(\bR\x12applyLevelDishMode\x127\n" +
	"\x18power_save_start_minutes\x18\x04 \x01(\rR\x15powerSaveStartMinutes\x12C\n" +
	"\x1eapply_power_save_start_minutes\x18\xa1\x1f \x01(\bR\x1aapplyPowerSaveStartMinutes\x12=\n" +
	"\x1bpower_save_duration_minutes\x18\x05 \x01(\rR\x18powerSaveDurationMinutes\x12I\n" +
	"!apply_power_save_duration_minutes\x18\x89' \x01(\bR\x1dapplyPowerSaveDurationMinutes\x12&\n" +
	"\x0fpower_save_mode\x18\x06 \x01(\bR\rpowerSaveMode\x122\n" +
	"\x15apply_power_save_mode\x18\xf1. \x01(\bR\x12applyPowerSaveMode\x120\n" +
	"\x14swupdate_reboot_hour\x18\t \x01(\rR\x12swupdateRebootHour\x12<\n" +
	"\x1aapply_swupdate_reboot_hour\x18\xa9F \x01(\bR\x17applySwupdateRebootHour\x12L\n" +
	"#swupdate_three_day_deferral_enabled\x18\a \x01(\bR\x1fswupdateThreeDayDeferralEnabled\x12X\n" +
	")apply_swupdate_three_day_deferral_enabled\x18\xd96 \x01(\bR$applySwupdateThreeDayDeferralEnabled\x12\x1f\n" +
	"\vasset_class\x18\b \x01(\rR\n" +
	"assetClass\x12+\n" +
	"\x11apply_asset_class\x18\xc1> \x01(\bR\x0fapplyAssetClass\"7\n" +
	"\fSnowMeltMode\x12\b\n" +
	"\x04AUTO\x10\x00\x12\r\n" +
	"\tALWAYS_ON\x10\x01\x12\x0e\n" +
	"\n" +
	"ALWAYS_OFF\x10\x02\"*\n" +
	"\x13LocationRequestMode\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05LOCAL\x10\x01\"6\n" +
	"\rLevelDishMode\x12\x14\n" +
	"\x10TILT_LIKE_NORMAL\x10\x00\x12\x0f\n" +
	"\vFORCE_LEVEL\x10\x01B\x17Z\x15spacex.com/api/deviceb\x06proto3"

var (
	file_spacex_api_device_dish_config_proto_rawDescOnce sync.Once
	file_spacex_api_device_dish_config_proto_rawDescData []byte
)

func file_spacex_api_device_dish_config_proto_rawDescGZIP() []byte {
	file_spacex_api_device_dish_config_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_dish_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacex_api_device_dish_config_proto_rawDesc), len(file_spacex_api_device_dish_config_proto_rawDesc)))
	})
	return file_spacex_api_device_dish_config_proto_rawDescData
}

var file_spacex_api_device_dish_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_spacex_api_device_dish_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spacex_api_device_dish_config_proto_goTypes = []any{
	(DishConfig_SnowMeltMode)(0),        // 0: SpaceX.API.Device.DishConfig.SnowMeltMode
	(DishConfig_LocationRequestMode)(0), // 1: SpaceX.API.Device.DishConfig.LocationRequestMode
	(DishConfig_LevelDishMode)(0),       // 2: SpaceX.API.Device.DishConfig.LevelDishMode
	(*DishConfig)(nil),                  // 3: SpaceX.API.Device.DishConfig
}
var file_spacex_api_device_dish_config_proto_depIdxs = []int32{
	0, // 0: SpaceX.API.Device.DishConfig.snow_melt_mode:type_name -> SpaceX.API.Device.DishConfig.SnowMeltMode
	1, // 1: SpaceX.API.Device.DishConfig.location_request_mode:type_name -> SpaceX.API.Device.DishConfig.LocationRequestMode
	2, // 2: SpaceX.API.Device.DishConfig.level_dish_mode:type_name -> SpaceX.API.Device.DishConfig.LevelDishMode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_spacex_api_device_dish_config_proto_init() }
func file_spacex_api_device_dish_config_proto_init() {
	if File_spacex_api_device_dish_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacex_api_device_dish_config_proto_rawDesc), len(file_spacex_api_device_dish_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_device_dish_config_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_dish_config_proto_depIdxs,
		EnumInfos:         file_spacex_api_device_dish_config_proto_enumTypes,
		MessageInfos:      file_spacex_api_device_dish_config_proto_msgTypes,
	}.Build()
	File_spacex_api_device_dish_config_proto = out.File
	file_spacex_api_device_dish_config_proto_goTypes = nil
	file_spacex_api_device_dish_config_proto_depIdxs = nil
}
