// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: spacex_api/device/gnss.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeReference int32

const (
	TimeReference_TIME_GPS     TimeReference = 0
	TimeReference_TIME_GALILEO TimeReference = 1
	TimeReference_TIME_BEIDOU  TimeReference = 2
	TimeReference_TIME_GLONASS TimeReference = 3
)

// Enum value maps for TimeReference.
var (
	TimeReference_name = map[int32]string{
		0: "TIME_GPS",
		1: "TIME_GALILEO",
		2: "TIME_BEIDOU",
		3: "TIME_GLONASS",
	}
	TimeReference_value = map[string]int32{
		"TIME_GPS":     0,
		"TIME_GALILEO": 1,
		"TIME_BEIDOU":  2,
		"TIME_GLONASS": 3,
	}
)

func (x TimeReference) Enum() *TimeReference {
	p := new(TimeReference)
	*p = x
	return p
}

func (x TimeReference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeReference) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_gnss_proto_enumTypes[0].Descriptor()
}

func (TimeReference) Type() protoreflect.EnumType {
	return &file_spacex_api_device_gnss_proto_enumTypes[0]
}

func (x TimeReference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeReference.Descriptor instead.
func (TimeReference) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{0}
}

type SatelliteSystem int32

const (
	SatelliteSystem_SYS_GPS        SatelliteSystem = 0
	SatelliteSystem_SYS_GALILEO    SatelliteSystem = 1
	SatelliteSystem_SYS_GLONASS    SatelliteSystem = 2
	SatelliteSystem_SYS_BEIDOU     SatelliteSystem = 3
	SatelliteSystem_SYS_SBAS       SatelliteSystem = 4
	SatelliteSystem_SYS_QZSS       SatelliteSystem = 5
	SatelliteSystem_SYS_IRNSS      SatelliteSystem = 6
	SatelliteSystem_SYS_STARLINK   SatelliteSystem = 7
	SatelliteSystem_SYS_STARSHIELD SatelliteSystem = 8
)

// Enum value maps for SatelliteSystem.
var (
	SatelliteSystem_name = map[int32]string{
		0: "SYS_GPS",
		1: "SYS_GALILEO",
		2: "SYS_GLONASS",
		3: "SYS_BEIDOU",
		4: "SYS_SBAS",
		5: "SYS_QZSS",
		6: "SYS_IRNSS",
		7: "SYS_STARLINK",
		8: "SYS_STARSHIELD",
	}
	SatelliteSystem_value = map[string]int32{
		"SYS_GPS":        0,
		"SYS_GALILEO":    1,
		"SYS_GLONASS":    2,
		"SYS_BEIDOU":     3,
		"SYS_SBAS":       4,
		"SYS_QZSS":       5,
		"SYS_IRNSS":      6,
		"SYS_STARLINK":   7,
		"SYS_STARSHIELD": 8,
	}
)

func (x SatelliteSystem) Enum() *SatelliteSystem {
	p := new(SatelliteSystem)
	*p = x
	return p
}

func (x SatelliteSystem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SatelliteSystem) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_gnss_proto_enumTypes[1].Descriptor()
}

func (SatelliteSystem) Type() protoreflect.EnumType {
	return &file_spacex_api_device_gnss_proto_enumTypes[1]
}

func (x SatelliteSystem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SatelliteSystem.Descriptor instead.
func (SatelliteSystem) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{1}
}

type CoordinateFrame int32

const (
	CoordinateFrame_ITRF CoordinateFrame = 0
	CoordinateFrame_ECEF CoordinateFrame = 1
	CoordinateFrame_GTRF CoordinateFrame = 2
	CoordinateFrame_PZ90 CoordinateFrame = 3
)

// Enum value maps for CoordinateFrame.
var (
	CoordinateFrame_name = map[int32]string{
		0: "ITRF",
		1: "ECEF",
		2: "GTRF",
		3: "PZ90",
	}
	CoordinateFrame_value = map[string]int32{
		"ITRF": 0,
		"ECEF": 1,
		"GTRF": 2,
		"PZ90": 3,
	}
)

func (x CoordinateFrame) Enum() *CoordinateFrame {
	p := new(CoordinateFrame)
	*p = x
	return p
}

func (x CoordinateFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoordinateFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_gnss_proto_enumTypes[2].Descriptor()
}

func (CoordinateFrame) Type() protoreflect.EnumType {
	return &file_spacex_api_device_gnss_proto_enumTypes[2]
}

func (x CoordinateFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoordinateFrame.Descriptor instead.
func (CoordinateFrame) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{2}
}

type Measurement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimeOfValidityNs int64                  `protobuf:"varint,1,opt,name=time_of_validity_ns,json=timeOfValidityNs,proto3" json:"time_of_validity_ns,omitempty"`
	SatelliteSystem  SatelliteSystem        `protobuf:"varint,2,opt,name=satellite_system,json=satelliteSystem,proto3,enum=SpaceX.API.Device.Gnss.SatelliteSystem" json:"satellite_system,omitempty"`
	Prn              int32                  `protobuf:"varint,3,opt,name=prn,proto3" json:"prn,omitempty"`
	Pseudorange      *Pseudorange           `protobuf:"bytes,4,opt,name=pseudorange,proto3" json:"pseudorange,omitempty"`
	Ephemeris        *Ephemeris             `protobuf:"bytes,5,opt,name=ephemeris,proto3" json:"ephemeris,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	mi := &file_spacex_api_device_gnss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{0}
}

func (x *Measurement) GetTimeOfValidityNs() int64 {
	if x != nil {
		return x.TimeOfValidityNs
	}
	return 0
}

func (x *Measurement) GetSatelliteSystem() SatelliteSystem {
	if x != nil {
		return x.SatelliteSystem
	}
	return SatelliteSystem_SYS_GPS
}

func (x *Measurement) GetPrn() int32 {
	if x != nil {
		return x.Prn
	}
	return 0
}

func (x *Measurement) GetPseudorange() *Pseudorange {
	if x != nil {
		return x.Pseudorange
	}
	return nil
}

func (x *Measurement) GetEphemeris() *Ephemeris {
	if x != nil {
		return x.Ephemeris
	}
	return nil
}

type Pseudorange struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PseudorangeM          float64                `protobuf:"fixed64,1,opt,name=pseudorange_m,json=pseudorangeM,proto3" json:"pseudorange_m,omitempty"`
	PseudorangeVarianceM2 float32                `protobuf:"fixed32,2,opt,name=pseudorange_variance_m2,json=pseudorangeVarianceM2,proto3" json:"pseudorange_variance_m2,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Pseudorange) Reset() {
	*x = Pseudorange{}
	mi := &file_spacex_api_device_gnss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pseudorange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pseudorange) ProtoMessage() {}

func (x *Pseudorange) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pseudorange.ProtoReflect.Descriptor instead.
func (*Pseudorange) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{1}
}

func (x *Pseudorange) GetPseudorangeM() float64 {
	if x != nil {
		return x.PseudorangeM
	}
	return 0
}

func (x *Pseudorange) GetPseudorangeVarianceM2() float32 {
	if x != nil {
		return x.PseudorangeVarianceM2
	}
	return 0
}

type Ephemeris struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SvDataTime      *SatnavTime            `protobuf:"bytes,1,opt,name=sv_data_time,json=svDataTime,proto3" json:"sv_data_time,omitempty"`
	CoordinateFrame CoordinateFrame        `protobuf:"varint,2,opt,name=coordinate_frame,json=coordinateFrame,proto3,enum=SpaceX.API.Device.Gnss.CoordinateFrame" json:"coordinate_frame,omitempty"`
	SvPosM          *Vector3               `protobuf:"bytes,3,opt,name=sv_pos_m,json=svPosM,proto3" json:"sv_pos_m,omitempty"`
	SvVelM          *Vector3               `protobuf:"bytes,4,opt,name=sv_vel_m,json=svVelM,proto3" json:"sv_vel_m,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ephemeris) Reset() {
	*x = Ephemeris{}
	mi := &file_spacex_api_device_gnss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ephemeris) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ephemeris) ProtoMessage() {}

func (x *Ephemeris) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ephemeris.ProtoReflect.Descriptor instead.
func (*Ephemeris) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{2}
}

func (x *Ephemeris) GetSvDataTime() *SatnavTime {
	if x != nil {
		return x.SvDataTime
	}
	return nil
}

func (x *Ephemeris) GetCoordinateFrame() CoordinateFrame {
	if x != nil {
		return x.CoordinateFrame
	}
	return CoordinateFrame_ITRF
}

func (x *Ephemeris) GetSvPosM() *Vector3 {
	if x != nil {
		return x.SvPosM
	}
	return nil
}

func (x *Ephemeris) GetSvVelM() *Vector3 {
	if x != nil {
		return x.SvVelM
	}
	return nil
}

type SatnavTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    uint32                 `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	SecondsOfWeek float64                `protobuf:"fixed64,2,opt,name=seconds_of_week,json=secondsOfWeek,proto3" json:"seconds_of_week,omitempty"`
	TimeReference TimeReference          `protobuf:"varint,3,opt,name=time_reference,json=timeReference,proto3,enum=SpaceX.API.Device.Gnss.TimeReference" json:"time_reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatnavTime) Reset() {
	*x = SatnavTime{}
	mi := &file_spacex_api_device_gnss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatnavTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatnavTime) ProtoMessage() {}

func (x *SatnavTime) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatnavTime.ProtoReflect.Descriptor instead.
func (*SatnavTime) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{3}
}

func (x *SatnavTime) GetWeekNumber() uint32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *SatnavTime) GetSecondsOfWeek() float64 {
	if x != nil {
		return x.SecondsOfWeek
	}
	return 0
}

func (x *SatnavTime) GetTimeReference() TimeReference {
	if x != nil {
		return x.TimeReference
	}
	return TimeReference_TIME_GPS
}

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_spacex_api_device_gnss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_gnss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_gnss_proto_rawDescGZIP(), []int{4}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_spacex_api_device_gnss_proto protoreflect.FileDescriptor

const file_spacex_api_device_gnss_proto_rawDesc = "" +
	"\n" +
	"\x1cspacex_api/device/gnss.proto\x12\x16SpaceX.API.Device.Gnss\"\xaa\x02\n" +
	"\vMeasurement\x12-\n" +
	"\x13time_of_validity_ns\x18\x01 \x01(\x03R\x10timeOfValidityNs\x12R\n" +
	"\x10satellite_system\x18\x02 \x01(\x0e2'.SpaceX.API.Device.Gnss.SatelliteSystemR\x0fsatelliteSystem\x12\x10\n" +
	"\x03prn\x18\x03 \x01(\x05R\x03prn\x12E\n" +
	"\vpseudorange\x18\x04 \x01(\v2#.SpaceX.API.Device.Gnss.PseudorangeR\vpseudorange\x12?\n" +
	"\tephemeris\x18\x05 \x01(\v2!.SpaceX.API.Device.Gnss.EphemerisR\tephemeris\"j\n" +
	"\vPseudorange\x12#\n" +
	"\rpseudorange_m\x18\x01 \x01(\x01R\fpseudorangeM\x126\n" +
	"\x17pseudorange_variance_m2\x18\x02 \x01(\x02R\x15pseudorangeVarianceM2\"\x9b\x02\n" +
	"\tEphemeris\x12D\n" +
	"\fsv_data_time\x18\x01 \x01(\v2\".SpaceX.API.Device.Gnss.SatnavTimeR\n" +
	"svDataTime\x12R\n" +
	"\x10coordinate_frame\x18\x02 \x01(\x0e2'.SpaceX.API.Device.Gnss.CoordinateFrameR\x0fcoordinateFrame\x129\n" +
	"\bsv_pos_m\x18\x03 \x01(\v2\x1f.SpaceX.API.Device.Gnss.Vector3R\x06svPosM\x129\n" +
	"\bsv_vel_m\x18\x04 \x01(\v2\x1f.SpaceX.API.Device.Gnss.Vector3R\x06svVelM\"\xa3\x01\n" +
	"\n" +
	"SatnavTime\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\rR\n" +
	"weekNumber\x12&\n" +
	"\x0fseconds_of_week\x18\x02 \x01(\x01R\rsecondsOfWeek\x12L\n" +
	"\x0etime_reference\x18\x03 \x01(\x0e2%.SpaceX.API.Device.Gnss.TimeReferenceR\rtimeReference\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z*R\n" +
	"\rTimeReference\x12\f\n" +
	"\bTIME_GPS\x10\x00\x12\x10\n" +
	"\fTIME_GALILEO\x10\x01\x12\x0f\n" +
	"\vTIME_BEIDOU\x10\x02\x12\x10\n" +
	"\fTIME_GLONASS\x10\x03*\xa1\x01\n" +
	"\x0fSatelliteSystem\x12\v\n" +
	"\aSYS_GPS\x10\x00\x12\x0f\n" +
	"\vSYS_GALILEO\x10\x01\x12\x0f\n" +
	"\vSYS_GLONASS\x10\x02\x12\x0e\n" +
	"\n" +
	"SYS_BEIDOU\x10\x03\x12\f\n" +
	"\bSYS_SBAS\x10\x04\x12\f\n" +
	"\bSYS_QZSS\x10\x05\x12\r\n" +
	"\tSYS_IRNSS\x10\x06\x12\x10\n" +
	"\fSYS_STARLINK\x10\a\x12\x12\n" +
	"\x0eSYS_STARSHIELD\x10\b*9\n" +
	"\x0fCoordinateFrame\x12\b\n" +
	"\x04ITRF\x10\x00\x12\b\n" +
	"\x04ECEF\x10\x01\x12\b\n" +
	"\x04GTRF\x10\x02\x12\b\n" +
	"\x04PZ90\x10\x03B\x17Z\x15spacex.com/api/deviceb\x06proto3"

var (
	file_spacex_api_device_gnss_proto_rawDescOnce sync.Once
	file_spacex_api_device_gnss_proto_rawDescData []byte
)

func file_spacex_api_device_gnss_proto_rawDescGZIP() []byte {
	file_spacex_api_device_gnss_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_gnss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacex_api_device_gnss_proto_rawDesc), len(file_spacex_api_device_gnss_proto_rawDesc)))
	})
	return file_spacex_api_device_gnss_proto_rawDescData
}

var file_spacex_api_device_gnss_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_spacex_api_device_gnss_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_spacex_api_device_gnss_proto_goTypes = []any{
	(TimeReference)(0),   // 0: SpaceX.API.Device.Gnss.TimeReference
	(SatelliteSystem)(0), // 1: SpaceX.API.Device.Gnss.SatelliteSystem
	(CoordinateFrame)(0), // 2: SpaceX.API.Device.Gnss.CoordinateFrame
	(*Measurement)(nil),  // 3: SpaceX.API.Device.Gnss.Measurement
	(*Pseudorange)(nil),  // 4: SpaceX.API.Device.Gnss.Pseudorange
	(*Ephemeris)(nil),    // 5: SpaceX.API.Device.Gnss.Ephemeris
	(*SatnavTime)(nil),   // 6: SpaceX.API.Device.Gnss.SatnavTime
	(*Vector3)(nil),      // 7: SpaceX.API.Device.Gnss.Vector3
}
var file_spacex_api_device_gnss_proto_depIdxs = []int32{
	1, // 0: SpaceX.API.Device.Gnss.Measurement.satellite_system:type_name -> SpaceX.API.Device.Gnss.SatelliteSystem
	4, // 1: SpaceX.API.Device.Gnss.Measurement.pseudorange:type_name -> SpaceX.API.Device.Gnss.Pseudorange
	5, // 2: SpaceX.API.Device.Gnss.Measurement.ephemeris:type_name -> SpaceX.API.Device.Gnss.Ephemeris
	6, // 3: SpaceX.API.Device.Gnss.Ephemeris.sv_data_time:type_name -> SpaceX.API.Device.Gnss.SatnavTime
	2, // 4: SpaceX.API.Device.Gnss.Ephemeris.coordinate_frame:type_name -> SpaceX.API.Device.Gnss.CoordinateFrame
	7, // 5: SpaceX.API.Device.Gnss.Ephemeris.sv_pos_m:type_name -> SpaceX.API.Device.Gnss.Vector3
	7, // 6: SpaceX.API.Device.Gnss.Ephemeris.sv_vel_m:type_name -> SpaceX.API.Device.Gnss.Vector3
	0, // 7: SpaceX.API.Device.Gnss.SatnavTime.time_reference:type_name -> SpaceX.API.Device.Gnss.TimeReference
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_spacex_api_device_gnss_proto_init() }
func file_spacex_api_device_gnss_proto_init() {
	if File_spacex_api_device_gnss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacex_api_device_gnss_proto_rawDesc), len(file_spacex_api_device_gnss_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_device_gnss_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_gnss_proto_depIdxs,
		EnumInfos:         file_spacex_api_device_gnss_proto_enumTypes,
		MessageInfos:      file_spacex_api_device_gnss_proto_msgTypes,
	}.Build()
	File_spacex_api_device_gnss_proto = out.File
	file_spacex_api_device_gnss_proto_goTypes = nil
	file_spacex_api_device_gnss_proto_depIdxs = nil
}
