// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: spacex_api/device/rssi_scan.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RssiEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ThetaDegree     float64                `protobuf:"fixed64,1,opt,name=theta_degree,json=thetaDegree,proto3" json:"theta_degree,omitempty"`
	PhiDegree       float64                `protobuf:"fixed64,2,opt,name=phi_degree,json=phiDegree,proto3" json:"phi_degree,omitempty"`
	RssiDbf         float64                `protobuf:"fixed64,3,opt,name=rssi_dbf,json=rssiDbf,proto3" json:"rssi_dbf,omitempty"`
	ScanTimestampMs uint64                 `protobuf:"varint,4,opt,name=scan_timestamp_ms,json=scanTimestampMs,proto3" json:"scan_timestamp_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RssiEntry) Reset() {
	*x = RssiEntry{}
	mi := &file_spacex_api_device_rssi_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RssiEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RssiEntry) ProtoMessage() {}

func (x *RssiEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_rssi_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RssiEntry.ProtoReflect.Descriptor instead.
func (*RssiEntry) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_rssi_scan_proto_rawDescGZIP(), []int{0}
}

func (x *RssiEntry) GetThetaDegree() float64 {
	if x != nil {
		return x.ThetaDegree
	}
	return 0
}

func (x *RssiEntry) GetPhiDegree() float64 {
	if x != nil {
		return x.PhiDegree
	}
	return 0
}

func (x *RssiEntry) GetRssiDbf() float64 {
	if x != nil {
		return x.RssiDbf
	}
	return 0
}

func (x *RssiEntry) GetScanTimestampMs() uint64 {
	if x != nil {
		return x.ScanTimestampMs
	}
	return 0
}

type DishActivateRssiScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishActivateRssiScan) Reset() {
	*x = DishActivateRssiScan{}
	mi := &file_spacex_api_device_rssi_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishActivateRssiScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishActivateRssiScan) ProtoMessage() {}

func (x *DishActivateRssiScan) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_rssi_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishActivateRssiScan.ProtoReflect.Descriptor instead.
func (*DishActivateRssiScan) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_rssi_scan_proto_rawDescGZIP(), []int{1}
}

func (x *DishActivateRssiScan) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type DishGetRssiScanResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Channel          uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	RequestTimestamp uint64                 `protobuf:"varint,3,opt,name=request_timestamp,json=requestTimestamp,proto3" json:"request_timestamp,omitempty"`
	NumberSamples    uint32                 `protobuf:"varint,4,opt,name=number_samples,json=numberSamples,proto3" json:"number_samples,omitempty"`
	RssiScanPoints   []*RssiEntry           `protobuf:"bytes,5,rep,name=rssi_scan_points,json=rssiScanPoints,proto3" json:"rssi_scan_points,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DishGetRssiScanResult) Reset() {
	*x = DishGetRssiScanResult{}
	mi := &file_spacex_api_device_rssi_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishGetRssiScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishGetRssiScanResult) ProtoMessage() {}

func (x *DishGetRssiScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_rssi_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishGetRssiScanResult.ProtoReflect.Descriptor instead.
func (*DishGetRssiScanResult) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_rssi_scan_proto_rawDescGZIP(), []int{2}
}

func (x *DishGetRssiScanResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DishGetRssiScanResult) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *DishGetRssiScanResult) GetRequestTimestamp() uint64 {
	if x != nil {
		return x.RequestTimestamp
	}
	return 0
}

func (x *DishGetRssiScanResult) GetNumberSamples() uint32 {
	if x != nil {
		return x.NumberSamples
	}
	return 0
}

func (x *DishGetRssiScanResult) GetRssiScanPoints() []*RssiEntry {
	if x != nil {
		return x.RssiScanPoints
	}
	return nil
}

var File_spacex_api_device_rssi_scan_proto protoreflect.FileDescriptor

const file_spacex_api_device_rssi_scan_proto_rawDesc = "" +
	"\n" +
	"!spacex_api/device/rssi_scan.proto\x12\x11SpaceX.API.Device\"\x94\x01\n" +
	"\tRssiEntry\x12!\n" +
	"\ftheta_degree\x18\x01 \x01(\x01R\vthetaDegree\x12\x1d\n" +
	"\n" +
	"phi_degree\x18\x02 \x01(\x01R\tphiDegree\x12\x19\n" +
	"\brssi_dbf\x18\x03 \x01(\x01R\arssiDbf\x12*\n" +
	"\x11scan_timestamp_ms\x18\x04 \x01(\x04R\x0fscanTimestampMs\"0\n" +
	"\x14DishActivateRssiScan\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\"\xe7\x01\n" +
	"\x15DishGetRssiScanResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12+\n" +
	"\x11request_timestamp\x18\x03 \x01(\x04R\x10requestTimestamp\x12%\n" +
	"\x0enumber_samples\x18\x04 \x01(\rR\rnumberSamples\x12F\n" +
	"\x10rssi_scan_points\x18\x05 \x03(\v2\x1c.SpaceX.API.Device.RssiEntryR\x0erssiScanPointsB\x17Z\x15spacex.com/api/deviceb\x06proto3"

var (
	file_spacex_api_device_rssi_scan_proto_rawDescOnce sync.Once
	file_spacex_api_device_rssi_scan_proto_rawDescData []byte
)

func file_spacex_api_device_rssi_scan_proto_rawDescGZIP() []byte {
	file_spacex_api_device_rssi_scan_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_rssi_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacex_api_device_rssi_scan_proto_rawDesc), len(file_spacex_api_device_rssi_scan_proto_rawDesc)))
	})
	return file_spacex_api_device_rssi_scan_proto_rawDescData
}

var file_spacex_api_device_rssi_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spacex_api_device_rssi_scan_proto_goTypes = []any{
	(*RssiEntry)(nil),             // 0: SpaceX.API.Device.RssiEntry
	(*DishActivateRssiScan)(nil),  // 1: SpaceX.API.Device.DishActivateRssiScan
	(*DishGetRssiScanResult)(nil), // 2: SpaceX.API.Device.DishGetRssiScanResult
}
var file_spacex_api_device_rssi_scan_proto_depIdxs = []int32{
	0, // 0: SpaceX.API.Device.DishGetRssiScanResult.rssi_scan_points:type_name -> SpaceX.API.Device.RssiEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spacex_api_device_rssi_scan_proto_init() }
func file_spacex_api_device_rssi_scan_proto_init() {
	if File_spacex_api_device_rssi_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacex_api_device_rssi_scan_proto_rawDesc), len(file_spacex_api_device_rssi_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_device_rssi_scan_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_rssi_scan_proto_depIdxs,
		MessageInfos:      file_spacex_api_device_rssi_scan_proto_msgTypes,
	}.Build()
	File_spacex_api_device_rssi_scan_proto = out.File
	file_spacex_api_device_rssi_scan_proto_goTypes = nil
	file_spacex_api_device_rssi_scan_proto_depIdxs = nil
}
