// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: spacex/api/satellites/network/ut_disablement_codes.proto

package network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UtDisablementCode int32

const (
	UtDisablementCode_UNKNOWN_STATE                 UtDisablementCode = 0
	UtDisablementCode_OKAY                          UtDisablementCode = 1
	UtDisablementCode_NO_ACTIVE_ACCOUNT             UtDisablementCode = 2
	UtDisablementCode_TOO_FAR_FROM_SERVICE_ADDRESS  UtDisablementCode = 3
	UtDisablementCode_IN_OCEAN                      UtDisablementCode = 4
	UtDisablementCode_BLOCKED_COUNTRY               UtDisablementCode = 6
	UtDisablementCode_DATA_OVERAGE_SANDBOX_POLICY   UtDisablementCode = 7
	UtDisablementCode_CELL_IS_DISABLED              UtDisablementCode = 8
	UtDisablementCode_ROAM_RESTRICTED               UtDisablementCode = 10
	UtDisablementCode_UNKNOWN_LOCATION              UtDisablementCode = 11
	UtDisablementCode_ACCOUNT_DISABLED              UtDisablementCode = 12
	UtDisablementCode_UNSUPPORTED_VERSION           UtDisablementCode = 13
	UtDisablementCode_MOVING_TOO_FAST_FOR_POLICY    UtDisablementCode = 14
	UtDisablementCode_UNDER_AVIATION_FLYOVER_LIMITS UtDisablementCode = 15
)

// Enum value maps for UtDisablementCode.
var (
	UtDisablementCode_name = map[int32]string{
		0:  "UNKNOWN_STATE",
		1:  "OKAY",
		2:  "NO_ACTIVE_ACCOUNT",
		3:  "TOO_FAR_FROM_SERVICE_ADDRESS",
		4:  "IN_OCEAN",
		6:  "BLOCKED_COUNTRY",
		7:  "DATA_OVERAGE_SANDBOX_POLICY",
		8:  "CELL_IS_DISABLED",
		10: "ROAM_RESTRICTED",
		11: "UNKNOWN_LOCATION",
		12: "ACCOUNT_DISABLED",
		13: "UNSUPPORTED_VERSION",
		14: "MOVING_TOO_FAST_FOR_POLICY",
		15: "UNDER_AVIATION_FLYOVER_LIMITS",
	}
	UtDisablementCode_value = map[string]int32{
		"UNKNOWN_STATE":                 0,
		"OKAY":                          1,
		"NO_ACTIVE_ACCOUNT":             2,
		"TOO_FAR_FROM_SERVICE_ADDRESS":  3,
		"IN_OCEAN":                      4,
		"BLOCKED_COUNTRY":               6,
		"DATA_OVERAGE_SANDBOX_POLICY":   7,
		"CELL_IS_DISABLED":              8,
		"ROAM_RESTRICTED":               10,
		"UNKNOWN_LOCATION":              11,
		"ACCOUNT_DISABLED":              12,
		"UNSUPPORTED_VERSION":           13,
		"MOVING_TOO_FAST_FOR_POLICY":    14,
		"UNDER_AVIATION_FLYOVER_LIMITS": 15,
	}
)

func (x UtDisablementCode) Enum() *UtDisablementCode {
	p := new(UtDisablementCode)
	*p = x
	return p
}

func (x UtDisablementCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UtDisablementCode) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_satellites_network_ut_disablement_codes_proto_enumTypes[0].Descriptor()
}

func (UtDisablementCode) Type() protoreflect.EnumType {
	return &file_spacex_api_satellites_network_ut_disablement_codes_proto_enumTypes[0]
}

func (x UtDisablementCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UtDisablementCode.Descriptor instead.
func (UtDisablementCode) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDescGZIP(), []int{0}
}

type AccountDisablementReason int32

const (
	AccountDisablementReason_NO_RESTRICTION              AccountDisablementReason = 0
	AccountDisablementReason_KNOW_YOUR_CUSTOMER_REQUIRED AccountDisablementReason = 1
)

// Enum value maps for AccountDisablementReason.
var (
	AccountDisablementReason_name = map[int32]string{
		0: "NO_RESTRICTION",
		1: "KNOW_YOUR_CUSTOMER_REQUIRED",
	}
	AccountDisablementReason_value = map[string]int32{
		"NO_RESTRICTION":              0,
		"KNOW_YOUR_CUSTOMER_REQUIRED": 1,
	}
)

func (x AccountDisablementReason) Enum() *AccountDisablementReason {
	p := new(AccountDisablementReason)
	*p = x
	return p
}

func (x AccountDisablementReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountDisablementReason) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_satellites_network_ut_disablement_codes_proto_enumTypes[1].Descriptor()
}

func (AccountDisablementReason) Type() protoreflect.EnumType {
	return &file_spacex_api_satellites_network_ut_disablement_codes_proto_enumTypes[1]
}

func (x AccountDisablementReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountDisablementReason.Descriptor instead.
func (AccountDisablementReason) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDescGZIP(), []int{1}
}

var File_spacex_api_satellites_network_ut_disablement_codes_proto protoreflect.FileDescriptor

const file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDesc = "" +
	"\n" +
	"8spacex/api/satellites/network/ut_disablement_codes.proto\x12\x1dSpaceX.API.Satellites.Network*\x91\x03\n" +
	"\x11UtDisablementCode\x12\x11\n" +
	"\rUNKNOWN_STATE\x10\x00\x12\b\n" +
	"\x04OKAY\x10\x01\x12\x15\n" +
	"\x11NO_ACTIVE_ACCOUNT\x10\x02\x12 \n" +
	"\x1cTOO_FAR_FROM_SERVICE_ADDRESS\x10\x03\x12\f\n" +
	"\bIN_OCEAN\x10\x04\x12\x13\n" +
	"\x0fBLOCKED_COUNTRY\x10\x06\x12\x1f\n" +
	"\x1bDATA_OVERAGE_SANDBOX_POLICY\x10\a\x12\x14\n" +
	"\x10CELL_IS_DISABLED\x10\b\x12\x13\n" +
	"\x0fROAM_RESTRICTED\x10\n" +
	"\x12\x14\n" +
	"\x10UNKNOWN_LOCATION\x10\v\x12\x14\n" +
	"\x10ACCOUNT_DISABLED\x10\f\x12\x17\n" +
	"\x13UNSUPPORTED_VERSION\x10\r\x12\x1e\n" +
	"\x1aMOVING_TOO_FAST_FOR_POLICY\x10\x0e\x12!\n" +
	"\x1dUNDER_AVIATION_FLYOVER_LIMITS\x10\x0f\"\x04\b\x05\x10\x05\"\x04\b\t\x10\t*\x0fINVALID_COUNTRY*\x12UNLICENSED_COUNTRY*O\n" +
	"\x18AccountDisablementReason\x12\x12\n" +
	"\x0eNO_RESTRICTION\x10\x00\x12\x1f\n" +
	"\x1bKNOW_YOUR_CUSTOMER_REQUIRED\x10\x01b\x06proto3"

var (
	file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDescOnce sync.Once
	file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDescData []byte
)

func file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDescGZIP() []byte {
	file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDescOnce.Do(func() {
		file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDesc), len(file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDesc)))
	})
	return file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDescData
}

var file_spacex_api_satellites_network_ut_disablement_codes_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spacex_api_satellites_network_ut_disablement_codes_proto_goTypes = []any{
	(UtDisablementCode)(0),        // 0: SpaceX.API.Satellites.Network.UtDisablementCode
	(AccountDisablementReason)(0), // 1: SpaceX.API.Satellites.Network.AccountDisablementReason
}
var file_spacex_api_satellites_network_ut_disablement_codes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spacex_api_satellites_network_ut_disablement_codes_proto_init() }
func file_spacex_api_satellites_network_ut_disablement_codes_proto_init() {
	if File_spacex_api_satellites_network_ut_disablement_codes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDesc), len(file_spacex_api_satellites_network_ut_disablement_codes_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_satellites_network_ut_disablement_codes_proto_goTypes,
		DependencyIndexes: file_spacex_api_satellites_network_ut_disablement_codes_proto_depIdxs,
		EnumInfos:         file_spacex_api_satellites_network_ut_disablement_codes_proto_enumTypes,
	}.Build()
	File_spacex_api_satellites_network_ut_disablement_codes_proto = out.File
	file_spacex_api_satellites_network_ut_disablement_codes_proto_goTypes = nil
	file_spacex_api_satellites_network_ut_disablement_codes_proto_depIdxs = nil
}
