// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: spacex_api/telemetron/public/integrations/rate_limit_reason.proto

package integrations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitReason int32

const (
	RateLimitReason_UNKNOWN                RateLimitReason = 0
	RateLimitReason_NO_LIMIT               RateLimitReason = 1
	RateLimitReason_POLICY_LIMIT           RateLimitReason = 2
	RateLimitReason_USER_CUSTOM_LIMIT      RateLimitReason = 3
	RateLimitReason_OVERAGE_LIMIT          RateLimitReason = 5
	RateLimitReason_LOW_SPEED_POLICY_LIMIT RateLimitReason = 6
)

// Enum value maps for RateLimitReason.
var (
	RateLimitReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "NO_LIMIT",
		2: "POLICY_LIMIT",
		3: "USER_CUSTOM_LIMIT",
		5: "OVERAGE_LIMIT",
		6: "LOW_SPEED_POLICY_LIMIT",
	}
	RateLimitReason_value = map[string]int32{
		"UNKNOWN":                0,
		"NO_LIMIT":               1,
		"POLICY_LIMIT":           2,
		"USER_CUSTOM_LIMIT":      3,
		"OVERAGE_LIMIT":          5,
		"LOW_SPEED_POLICY_LIMIT": 6,
	}
)

func (x RateLimitReason) Enum() *RateLimitReason {
	p := new(RateLimitReason)
	*p = x
	return p
}

func (x RateLimitReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateLimitReason) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_enumTypes[0].Descriptor()
}

func (RateLimitReason) Type() protoreflect.EnumType {
	return &file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_enumTypes[0]
}

func (x RateLimitReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateLimitReason.Descriptor instead.
func (RateLimitReason) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDescGZIP(), []int{0}
}

var File_spacex_api_telemetron_public_integrations_rate_limit_reason_proto protoreflect.FileDescriptor

const file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDesc = "" +
	"\n" +
	"Aspacex_api/telemetron/public/integrations/rate_limit_reason.proto\x12)SpaceX.API.Telemetron.Public.Integrations*\xa1\x01\n" +
	"\x0fRateLimitReason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bNO_LIMIT\x10\x01\x12\x10\n" +
	"\fPOLICY_LIMIT\x10\x02\x12\x15\n" +
	"\x11USER_CUSTOM_LIMIT\x10\x03\x12\x11\n" +
	"\rOVERAGE_LIMIT\x10\x05\x12\x1a\n" +
	"\x16LOW_SPEED_POLICY_LIMIT\x10\x06\"\x04\b\x04\x10\x04*\x15HIGH_HOURLY_AVG_LIMITB?Z=spacex.com/api/telemetron/public/integrations/ratelimitreasonb\x06proto3"

var (
	file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDescOnce sync.Once
	file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDescData []byte
)

func file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDescGZIP() []byte {
	file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDescOnce.Do(func() {
		file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDesc), len(file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDesc)))
	})
	return file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDescData
}

var file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_goTypes = []any{
	(RateLimitReason)(0), // 0: SpaceX.API.Telemetron.Public.Integrations.RateLimitReason
}
var file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_init() }
func file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_init() {
	if File_spacex_api_telemetron_public_integrations_rate_limit_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDesc), len(file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_goTypes,
		DependencyIndexes: file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_depIdxs,
		EnumInfos:         file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_enumTypes,
	}.Build()
	File_spacex_api_telemetron_public_integrations_rate_limit_reason_proto = out.File
	file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_goTypes = nil
	file_spacex_api_telemetron_public_integrations_rate_limit_reason_proto_depIdxs = nil
}
