// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: spacex_api/device/services/unlock/service.proto

package unlock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnlockChallenge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nonce           []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	SignSpki        []byte                 `protobuf:"bytes,4,opt,name=sign_spki,json=signSpki,proto3" json:"sign_spki,omitempty"`
	GrantKeydata    string                 `protobuf:"bytes,5,opt,name=grant_keydata,json=grantKeydata,proto3" json:"grant_keydata,omitempty"`
	ServiceKeydata  string                 `protobuf:"bytes,6,opt,name=service_keydata,json=serviceKeydata,proto3" json:"service_keydata,omitempty"`
	AuthorityGrants []string               `protobuf:"bytes,7,rep,name=authority_grants,json=authorityGrants,proto3" json:"authority_grants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnlockChallenge) Reset() {
	*x = UnlockChallenge{}
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockChallenge) ProtoMessage() {}

func (x *UnlockChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockChallenge.ProtoReflect.Descriptor instead.
func (*UnlockChallenge) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_services_unlock_service_proto_rawDescGZIP(), []int{0}
}

func (x *UnlockChallenge) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UnlockChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *UnlockChallenge) GetSignSpki() []byte {
	if x != nil {
		return x.SignSpki
	}
	return nil
}

func (x *UnlockChallenge) GetGrantKeydata() string {
	if x != nil {
		return x.GrantKeydata
	}
	return ""
}

func (x *UnlockChallenge) GetServiceKeydata() string {
	if x != nil {
		return x.ServiceKeydata
	}
	return ""
}

func (x *UnlockChallenge) GetAuthorityGrants() []string {
	if x != nil {
		return x.AuthorityGrants
	}
	return nil
}

type StartUnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartUnlockRequest) Reset() {
	*x = StartUnlockRequest{}
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartUnlockRequest) ProtoMessage() {}

func (x *StartUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartUnlockRequest.ProtoReflect.Descriptor instead.
func (*StartUnlockRequest) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_services_unlock_service_proto_rawDescGZIP(), []int{1}
}

type StartUnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	SignSpki      []byte                 `protobuf:"bytes,3,opt,name=sign_spki,json=signSpki,proto3" json:"sign_spki,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartUnlockResponse) Reset() {
	*x = StartUnlockResponse{}
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartUnlockResponse) ProtoMessage() {}

func (x *StartUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartUnlockResponse.ProtoReflect.Descriptor instead.
func (*StartUnlockResponse) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_services_unlock_service_proto_rawDescGZIP(), []int{2}
}

func (x *StartUnlockResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StartUnlockResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *StartUnlockResponse) GetSignSpki() []byte {
	if x != nil {
		return x.SignSpki
	}
	return nil
}

type FinishUnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishUnlockRequest) Reset() {
	*x = FinishUnlockRequest{}
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishUnlockRequest) ProtoMessage() {}

func (x *FinishUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishUnlockRequest.ProtoReflect.Descriptor instead.
func (*FinishUnlockRequest) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_services_unlock_service_proto_rawDescGZIP(), []int{3}
}

func (x *FinishUnlockRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *FinishUnlockRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type FinishUnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishUnlockResponse) Reset() {
	*x = FinishUnlockResponse{}
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishUnlockResponse) ProtoMessage() {}

func (x *FinishUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_services_unlock_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishUnlockResponse.ProtoReflect.Descriptor instead.
func (*FinishUnlockResponse) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_services_unlock_service_proto_rawDescGZIP(), []int{4}
}

func (x *FinishUnlockResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_spacex_api_device_services_unlock_service_proto protoreflect.FileDescriptor

const file_spacex_api_device_services_unlock_service_proto_rawDesc = "" +
	"\n" +
	"/spacex_api/device/services/unlock/service.proto\x12!SpaceX.API.Device.Services.Unlock\"\xec\x01\n" +
	"\x0fUnlockChallenge\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1b\n" +
	"\tsign_spki\x18\x04 \x01(\fR\bsignSpki\x12#\n" +
	"\rgrant_keydata\x18\x05 \x01(\tR\fgrantKeydata\x12'\n" +
	"\x0fservice_keydata\x18\x06 \x01(\tR\x0eserviceKeydata\x12)\n" +
	"\x10authority_grants\x18\a \x03(\tR\x0fauthorityGrantsJ\x04\b\x03\x10\x04R\n" +
	"grant_spki\"\x14\n" +
	"\x12StartUnlockRequest\"e\n" +
	"\x13StartUnlockResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1b\n" +
	"\tsign_spki\x18\x03 \x01(\fR\bsignSpki\"Q\n" +
	"\x13FinishUnlockRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\".\n" +
	"\x14FinishUnlockResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status2\x8e\x02\n" +
	"\rUnlockService\x12|\n" +
	"\vStartUnlock\x125.SpaceX.API.Device.Services.Unlock.StartUnlockRequest\x1a6.SpaceX.API.Device.Services.Unlock.StartUnlockResponse\x12\x7f\n" +
	"\fFinishUnlock\x126.SpaceX.API.Device.Services.Unlock.FinishUnlockRequest\x1a7.SpaceX.API.Device.Services.Unlock.FinishUnlockResponseb\x06proto3"

var (
	file_spacex_api_device_services_unlock_service_proto_rawDescOnce sync.Once
	file_spacex_api_device_services_unlock_service_proto_rawDescData []byte
)

func file_spacex_api_device_services_unlock_service_proto_rawDescGZIP() []byte {
	file_spacex_api_device_services_unlock_service_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_services_unlock_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spacex_api_device_services_unlock_service_proto_rawDesc), len(file_spacex_api_device_services_unlock_service_proto_rawDesc)))
	})
	return file_spacex_api_device_services_unlock_service_proto_rawDescData
}

var file_spacex_api_device_services_unlock_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_spacex_api_device_services_unlock_service_proto_goTypes = []any{
	(*UnlockChallenge)(nil),      // 0: SpaceX.API.Device.Services.Unlock.UnlockChallenge
	(*StartUnlockRequest)(nil),   // 1: SpaceX.API.Device.Services.Unlock.StartUnlockRequest
	(*StartUnlockResponse)(nil),  // 2: SpaceX.API.Device.Services.Unlock.StartUnlockResponse
	(*FinishUnlockRequest)(nil),  // 3: SpaceX.API.Device.Services.Unlock.FinishUnlockRequest
	(*FinishUnlockResponse)(nil), // 4: SpaceX.API.Device.Services.Unlock.FinishUnlockResponse
}
var file_spacex_api_device_services_unlock_service_proto_depIdxs = []int32{
	1, // 0: SpaceX.API.Device.Services.Unlock.UnlockService.StartUnlock:input_type -> SpaceX.API.Device.Services.Unlock.StartUnlockRequest
	3, // 1: SpaceX.API.Device.Services.Unlock.UnlockService.FinishUnlock:input_type -> SpaceX.API.Device.Services.Unlock.FinishUnlockRequest
	2, // 2: SpaceX.API.Device.Services.Unlock.UnlockService.StartUnlock:output_type -> SpaceX.API.Device.Services.Unlock.StartUnlockResponse
	4, // 3: SpaceX.API.Device.Services.Unlock.UnlockService.FinishUnlock:output_type -> SpaceX.API.Device.Services.Unlock.FinishUnlockResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spacex_api_device_services_unlock_service_proto_init() }
func file_spacex_api_device_services_unlock_service_proto_init() {
	if File_spacex_api_device_services_unlock_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spacex_api_device_services_unlock_service_proto_rawDesc), len(file_spacex_api_device_services_unlock_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spacex_api_device_services_unlock_service_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_services_unlock_service_proto_depIdxs,
		MessageInfos:      file_spacex_api_device_services_unlock_service_proto_msgTypes,
	}.Build()
	File_spacex_api_device_services_unlock_service_proto = out.File
	file_spacex_api_device_services_unlock_service_proto_goTypes = nil
	file_spacex_api_device_services_unlock_service_proto_depIdxs = nil
}
